### ISSUE TITLE
Text wrapping in plot_confusion_matrix

### ISSUE THREAD

**Issue by michaelshekasta** [idanmoradarthas/DataScienceUtils#29]
Hi,

When I rename the class names, it's wrapping on "Accuracy" and "F1" measure.

Regards,
Michael

**Comment by idanmoradarthas** [comment]
I tried to recreate the problem:
I got:
![test_plot_confusion_matrix_issue_29](https://user-images.githubusercontent.com/14873156/100443859-2603e200-30b3-11eb-95f2-e8c846a9e51b.png)
Try to update your matplotlib and seaborn.
 Ether way you can control the size of image using:
```python
pyplot.gcf().set_size_inches(10, 8)
```
