### ISSUE TITLE
rename issue in "plot_magnitude_vs_cardinality"

### ISSUE THREAD

**Issue by refael1** [idanmoradarthas/DataScienceUtils#31]
In "def plot_magnitude_vs_cardinality" you need to fix the line code  to "cardinality = cardinality.rename(columns={"count": "cardinality"})" otherwise there is an error raised "KeyError: 'Cardinality'"

**Comment by idanmoradarthas** [comment]
Hi @refael1,
Thanks for pointing the problem. I can see it because the package is not updated with the latest python and package.  I'll try and work on it in the coming days.

**Comment by refael1** [comment]
best simple way - rename using: "cardinality.columns = ['cardinality']"

**Comment by idanmoradarthas** [comment]
Hi @refael1 
I updated and fixed the problem.
you can update your package from pypi or install it from the release page.
I will upload the new version to my anaconda channel in the coming days.

Thanks,

**Comment by idanmoradarthas** [comment]
The anaconda channel has been updated

**Comment by refael1** [comment]
Great👏. Will update today👍
